### ISSUE TITLE
Having "yeti 1" in the familiars list forces restarts upon encountering familiars

### ISSUE THREAD

**Issue by EricSpeidel** [Betalord/BHBot#48] opened 2019-03-30 20:02 UTC
Using the latest version and repository - this happens consistently, at least when doing z2d1. 

Upon encountering a familiar, after the view button has been clicked, an emergency restart is triggered.

Settings: 
```
persuasionLevel 1
bribeLevel 4
```
To reproduce, this will force restarts:

`familiars squib 1; driffin 1; violace 1; krackers 1; yeti 1`

while leaving out the yeti will work just fine:

`familiars squib 1; driffin 1; violace 1; krackers 1`

It happens when ANY familiar is encountered, doesn't have to be Yeti himself, but he needs to be in that list. 

Is this maybe an issue with the cues for Yeti, or a typo somewhere? Seems quite odd to me. Reinstalling Chromium and recloning from scratch did not fix the issue for me.

**Comment by ilpersi** [comment] 2019-03-30 20:46
Is there any error log? Usually if an emergency restart is performed the bot is printing the root cause of the error in the console.

**Comment by EricSpeidel** [comment] 2019-03-30 21:02
Thanks for the reply and great work keeping this up! 
Unfortunately, there is not. 

```
<2019/03/30 21:59:55> Attempting Heroic z2d1
<2019/03/30 22:00:09> Dungeon <z2d1> initiated!
<2019/03/30 22:00:48> Familiar encountered
<2019/03/30 22:01:13> Doing driver emergency restart...
Starting ChromeDriver 2.44.609538 (b655c5a60b0b544917107a59d4153d4bf78e1b90) on port 30437
Only local connections are allowed.
<2019/03/30 22:01:27> Game element found. Starting to run bot..
```

**Comment by ilpersi** [comment] 2019-03-31 08:05
I reviewed the code and there are a couple of restarts without log so something unexpected is happening and BHBot is not logging correctly. I will fix this with better logging.

Meanwhile I ask you one more confirmation: can you please double check that the Yeti.png is only present in the _cues\familiars\new_format_ path and **NOT** in the _cues\familiars\old_format_ one?

Thank you.

**Comment by EricSpeidel** [comment] 2019-03-31 08:59
I appreciate it. Yes, it is only present in the new_format folder.

**Comment by ilpersi** [comment] 2019-03-31 09:11
I've released [v34.2alpha2](https://github.com/Betalord/BHBot/releases/tag/v34.2a2) with improved logging. I did not have time to test it carefully, this is why it is alpha. There are small changes, so I don't expect issues.

**Comment by EricSpeidel** [comment] 2019-03-31 09:23
I'll test again later, maybe we get a more meaningful error now.

**Comment by ilpersi** [comment] 2019-03-31 09:23
Sorry for multiple posting: I reviewed one again the code and I think I've got the idea of what is happening.

I am almost sure the offending settings is `krackers 1`.

As a temporary workaround try to switch the order:
`familiars squib 1; driffin 1; violace 1; yeti 1; krackers 1`

If this i not working either, please try to remove it completely:
`familiars squib 1; driffin 1; violace 1; yeti 1`

I am sorry for this, the possible fix may require a review of the logic and some extended tests that will require a bit of time to complete.

**Comment by EricSpeidel** [comment] 2019-03-31 10:20
Switching the order did the trick, thanks! Will keep an eye open if krackers causes trouble elsewhere.

**Comment by ilpersi** [comment] 2019-03-31 12:01
Commit f250ef2708fea7f56489f8cca9fe961eb761191f should fix the issue, I am currently testing it. Usually I let the bot running a couple of days to be sure everything is fine. The current release does not include this fix yet.

BTW I really appreciate you people reporting issues. 👍

**Comment by EricSpeidel** [comment] 2019-03-31 12:44
That is great news, I really appreciate it! Glad you guys are keeping it alive, I'll be happy to collaborate when I get the time

**Comment by ilpersi** [comment] 2019-04-02 16:28
The new release with improved logic and a fix to this is not out. Please also make sure to update your cue/familiars folder as many cues have been moved to the new format.

I am going to close this, if the issue happens again please open a new issue.

**Closed by ilpersi** 2019-04-02 16:28 UTC
Labels: bug
