### ISSUE TITLE
Add timestamp to screenshots

### ISSUE THREAD

**Issue by testblubgangu** [Betalord/BHBot#72] opened 2019-05-02 20:23 UTC
So I just tested to PM screenshot feature and realized that screenshots with the same date get replaced. Some people - including me - get a lot of PMs per day and some of them are important.

It would be really useful to save all PMs you receive so you can check on them later.

**Comment by ilpersi** [comment] 2019-05-02 21:15
Screenshot are never replaced: when they are for the same date a progressive suffix is added to them. Like `_1`,` _2` and so on.

I've just double checked the code and I can confirm this holds true also for PM.

Here is how the name is composed:
`name = prefix + "_" + dateFormat.format(date) + "_" + num + ".png";`

**Comment by testblubgangu** [comment] 2019-05-02 22:56
Yeah I just checked it myself and for some reason f.exists() doesn't seem to work for me.

As you can see in the attachment the file gets created and is modified some hours later:
![grafik](https://user-images.githubusercontent.com/50218060/57111540-cf9aba00-6d3c-11e9-9c8a-acfa17507378.png)

Just tested it again to verify this behavior. Probably only an issue with my system.
Java version is 12.0.1 and OS is Win10 64 Bit.

According to this [stackoverflow thread](https://stackoverflow.com/questions/919918/file-exists-returns-false-when-file-exists) the following Java bug could be the reason: [JDK-4483097](https://bugs.java.com/bugdatabase/view_bug.do;:YfiG?bug_id=4483097)
A possible solution could be the use of `f.getAbsoluteFile().exists()` instead of `f.exists()`.

**Comment by ilpersi** [comment] 2019-05-03 05:41
I never tried with Java 12 as the bot requires java 8. The bug you linked is for Java 4 BTW.

Can you please try to move the bot out of the C:\Users path and give it a dedicated folder in C:\?

**Comment by ilpersi** [comment] 2019-05-05 19:17
@testblubgangu Have you been able to test the workaround I proposed you?

**Comment by ilpersi** [comment] 2019-05-12 09:20
I've got no feedback in one week, so I am closing this.

**Closed by ilpersi** 2019-05-12 09:20 UTC
Labels: enhancement

**Comment by ilpersi** [comment] 2019-05-14 16:19
After closing the issue, I've found what the issue is and this is now fixed in [v39.1](https://github.com/Betalord/BHBot/releases/tag/v39.1), check it out.
