### ISSUE TITLE
auto functions

### ISSUE THREAD

**Issue by zenblob** [Betalord/BHBot#29] opened 2019-03-07 08:04 UTC
Hi and thanks for your activity.
I'm a little confused: 
auto shrine causes problems both activated and deactivated.
Perhaps it is more correct to say that it creates anomalies even when deactivated.
Probably I am clumsy, but I get stuck often because of unexpected windows or other problems due to auto-shrine (and auto-revive).
I was also blocked by kongregate for trying too many times to login, I do not know how it could happen, I was afk
I remain at your disposal to answer more precise questions and I hope to be of help

**Comment by Fortigate** [comment] 2019-03-08 09:34
autoRevive I've been running with 5 accounts for two weeks without any issues, I have a few small failsafes I want to add add to it just to make sure that it's completely stable, but I'd be interested to here any issues other people are having with it.

autoShrine was a rushed feature and should probably be labelled as a beta feature until I find the time to look at it properly, it has some funny interactions with autoRevive as they both rely on Autopilot statuses, best thing to  do for now is to set the battleTimer to 45-60 seconds. The next version will have a dungeon time limit before re-enabling shrines/boss to prevent getting stuck to fix one of the main issues with it.

**Comment by zenblob** [comment] 2019-03-08 18:17
I mean problems like this: for example in this case the function was disabled, (set to 0)
![cattura](https://user-images.githubusercontent.com/48311971/54047137-8adc2200-41d6-11e9-8a1a-736d68024619.PNG)

**Comment by Larrush** [comment] 2019-03-08 23:08
What you mean is not necessarily a problem but a delay in workspeed due to the bot checking if its turned off.
This is more of a safety precaution since having these features on might lead to a crash.

The bot also does that with the autobribe function on zero. 
He still checks if he needs to bribe a familiar even if turned off. 
I don't mind it as long as it works ^^

**Comment by Fortigate** [comment] 2019-03-09 15:08
> I mean problems like this: for example in this case the function was disabled, (set to 0)
> ![cattura](https://user-images.githubusercontent.com/48311971/54047137-8adc2200-41d6-11e9-8a1a-736d68024619.PNG)

The first shrine check is intended behaviour, if you start the bot with autoShrine disabled it will do a one time check and disable just to make sure that it doesn't get stuck with the ignore flags enabled. Second one is a failsafe as the bot would enable the settings, and then check the shard count and not disable them if the shard count wasn't met, leading to it getting confused when it ran a dungeon/trials next.

I'll update the text to make it clearer what its doing, and skip the second failsafe running if autoShrines disabled.

**Comment by Fortigate** [comment] 2019-03-09 15:10
> The bot also does that with the autobribe function on zero.
> He still checks if he needs to bribe a familiar even if turned off.
> I don't mind it as long as it works ^^

Hah that never occurred to me, I was annoyed with it slowing down dungeon runs with bribing disabled as well. Just changed it to skip the familiar check when bribing's disabled and persuade instead.

**Comment by Larrush** [comment] 2019-03-11 17:42
I just wanted to throw a question out because of the "update" to maven.
Is it now possible to make ads work with the bot or is that a different issue?

**Comment by Fortigate** [comment] 2019-03-11 21:38
@ilpersi might be able to have a look at it, when I try my client says 'looking for ads' for 30 seconds then says no offers available so I can't work on implementing it.

**Comment by Larrush** [comment] 2019-03-11 21:41
I know this might sound stupid but do you use some kind of adblock, vpn or something else that changes the way your browser works.

That used to be a problem for me.
Or it might be a regional problem. Sinxe I guess BH uses google for ads they are always regional and if there are no ads in that country you can't receice any.

But I might be totally wrong 🙈

**Comment by ilpersi** [comment] 2019-03-12 06:06
@Larrush update to Maven is to manage dependencies more easily. If you look at the latest commits you will notice that I started to work on a [Pushover](https://pushover.net/) integration so you can be notified on your phone about how the bot is doing. Using Maven I only had to write a few lines of code to do it.

To be honest ADS are not on my priority list right now: last time I checked at them a lot of code was required to manage them and in my opinion, considering the gain, I am not sure if it is worth it.

Here is a sneak peek of how the pushover integration looks on my phone. 🤣 

[![97UZIk0S9o.png](https://i.imgur.com/SYdQUSb.jpg)](https://i.imgur.com/SYdQUSb.jpg)

**Comment by Larrush** [comment] 2019-03-12 09:51
Hehe that looks nice with the pushover integration 😁

I'll take a look at the ads today or tomorrow if it is a problem with the chrome edition.
Maybe it ia a safety precaution not to show ads when having chrome automation active.

If so there is no need to check that feature anyways ^^

**Comment by Larrush** [comment] 2019-03-12 21:11
Ok, it seems that either Chromium or the chrome automation extension, is prohibited by Kongregate.
At least when it comes to Ads.

Which I find even more interesting that they don´t mind us using the bot, but looking at Ads is too much to expect.

Well I guess in that case, those few Gems will be wasted xD

**Comment by ilpersi** [comment] 2019-03-13 07:53
We can switch back to Chrome and maybe also update to a more recent and secure version of it (Chrome 73) if this can help with ADS.

**Comment by Larrush** [comment] 2019-03-13 09:20
It might do, I am not sure if its just chromium or the extension.

**Comment by Fortigate** [comment] 2019-03-13 22:56
@ilpersi The reason we are on Chromium is that Chrome auto-updates, and after v69 they removed the ephemereal-flash-permissions flag allowing you to always allow flash, else you need to manually allow it each time you start the browser. Plus with Chromium you can hide the window and continue to use Chrome, for those who use it as their primary browser.

Selenium can apply flags and settings to Chromium as well so maybe there is a workaround going forward (we shouldn't stay on v69 forever) but I've not looked into it.

**Comment by zenblob** [comment] 2019-03-13 23:43
The meaning of my post is very much diverted. Returning to the initial point
I'm probably wrong ... but I can't understand what.
since I can't see them working, I'm trying to keep the automatic functions turned off.
unfortunately with these settings this happens:
![autorevive-autoshrine](https://user-images.githubusercontent.com/48311971/54321602-23690c80-45f2-11e9-8d25-03c8b68ad3e8.png)
![autorevive-autoshrine2](https://user-images.githubusercontent.com/48311971/54321614-3085fb80-45f2-11e9-9e33-b5c662b21ee8.png)

**Comment by Larrush** [comment] 2019-03-13 23:48
Did you get the latest master, that came out yesterday?

For me all the issues with Shrine are fixed with the newest version.
Do you hide the windowonrestart?

**Comment by zenblob** [comment] 2019-03-14 00:01
I have the latest release: v33.  
I don't hide the window, the bot runs on a virtual machine that is never disturbed.

**Comment by Larrush** [comment] 2019-03-14 00:06
It's in the masterversion of the bot not in the v33 release.

You have to download the clone in the "code" tab and either replace the old files with the new ones or just put the .bat and.jar file into the masterfolder.

The newest updates are not in full release yet.

**Comment by Larrush** [comment] 2019-03-17 16:03
He did it again :O 
![Untitled](https://user-images.githubusercontent.com/47528224/54494043-6d920c80-48d6-11e9-85b2-e56309be2450.jpg)
![Untitled](https://user-images.githubusercontent.com/47528224/54494051-8995ae00-48d6-11e9-8d3a-da685835d28e.jpg)

I have the newest master, so it seems he still gets confused by this

**Comment by ilpersi** [comment] 2019-04-10 20:01
Autoshrine is being addressed in issue #40 and I recently committed a couple of fixes. I am closing this issue, if there are still problems, please use #40.

**Closed by ilpersi** 2019-04-10 20:01 UTC
