### ISSUE TITLE
BHBot keeps crashing on startup

### ISSUE THREAD

**Issue by Larrush** [Betalord/BHBot#69] opened 2019-04-20 20:09 UTC
With the new master and the V36 .jar the .bat always crashes on startup.

It starts up for a second shows a few lines, and immediatley dissapears.
This usually happened when I had something wrong in my settings, but I tried it with the default settings.ini and it still crashes

It doesn´t even give me a crashnote. 
If I start the init.bat he starts up with no problems.

Any Ideas what could be the problem? 
**Desktop (please complete the following information):**
Windows 10
Chromium

**Comment by ilpersi** [comment] 2019-04-20 20:30
If you don't start from the init.bat how else do you start it? Can you please paste the start-up log?

**Comment by Larrush** [comment] 2019-04-20 20:41
That's the problem. I can't.

The init.bat starts up with no problems but the bhbot.bat starts up shows the cmdwindow for like a second.
I can see he posts a few lines and then he crashes.
There is no time to copy anything thats going to be written.

I redownloaded everything from scratch made a complete default folder, still happens.

I'll keep trying to figure out the problem but maybe you can think of something that I forget ^^

**Comment by ilpersi** [comment] 2019-04-20 20:55
Please don't run the bat file with a double click on it, but manually from a windows CMD prompt.

**Comment by Larrush** [comment] 2019-04-20 21:09
If I open the cmd windows and type:
`C:\Users\Larry>start C:\Users\Larry\Downloads\BHBot-master\bhbot.bat`

he opens a new CMD windows and shows me this:
```
Error: Unable to access jarfile BHBot.jar

C:\Users\Larry>

```

When starting the cmd as admin it´s the same.

Should I use another code? 
I am really not the best with CMD commands, so this might get tricky :( 
Sorry about that!

**Comment by Larrush** [comment] 2019-04-20 21:12
This is what is beeing showed in the init.bat at startup
```
<2019/04/20 23:11:22> BHBot v36 started.
<2019/04/20 23:11:23> Found 3 familiar cue(s) with old format.
<2019/04/20 23:11:23> Found 107 familiar cue(s) with new format.
<2019/04/20 23:11:23> Idle mode started, no actions will be taken
<2019/04/20 23:11:23> Found Chromium in C:\Users\Larry\AppData\Local\Chromium\Application\chrome.exe
<2019/04/20 23:11:23> Found chromedriver in C:\Users\Larry\Downloads\BHBot-master\chromedriver.exe
<2019/04/20 23:11:23> Found cues in C:\Users\Larry\Downloads\BHBot-master\cues
<2019/04/20 23:11:23> Found screenshots in C:\Users\Larry\Downloads\BHBot-master\screenshots
<2019/04/20 23:11:23> Driver started succesfully
Starting ChromeDriver 2.44.609538 (b655c5a60b0b544917107a59d4153d4bf78e1b90) on port ***
Only local connections are allowed.
```

**Comment by Larrush** [comment] 2019-04-20 21:14
weirdly enough when I open the init.bat over the CMD window I get the same Issue as when I try to open BHBot.bat

**Comment by irissian** [comment] 2019-04-20 21:16
I confirm the same issue here, both on a compiled version of the last files and the release.

**Comment by Larrush** [comment] 2019-04-20 21:18
I think there is a problem with the BHBot.jar. 
But I don´t know for sure.

I just opened the properties of the .jar and it showed me that this file is from another pc and might be blocked.

Now I unblocked it, and turned off my Antivirus for a bit, but that didn´t help either.

Sorry for posting so much information, I just don´t know what could help you, helping us^^

**Comment by BagOfIce** [comment] 2019-04-20 21:42
I get the same issue. In the settings file removing "autoRevive t g r e" allows the bot to start without issue.

I added a pause line to the bat file and the error is:
Exception in thread "main" java.lang.NumberFormatException: For input string: "t g r e"
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at Settings.load(Settings.java:534)
        at Settings.load(Settings.java:583)
        at BHBot.processCommand(BHBot.java:220)
        at BHBot.main(BHBot.java:73)

**Comment by ilpersi** [comment] 2019-04-20 21:55
I do not recommend to put BHBot under the Download folder.
Please have a dedicated folder in your root drive (e.g. C:\).

I've released a new version up to date with all the latest updates, including support for the Jimmie Expedition.

**Comment by Larrush** [comment] 2019-04-20 21:58
I´ve found the Issue! 

It is this Line
`autoRevive t g r e
`
It should look like this
`autorevive t g r e`

The big R messes up the bot

**Comment by ilpersi** [comment] 2019-04-20 22:05
The bot is expecting autoRevive (with the capital R) and the issue is due to the fact that the format has been changed to also include expedition support.

Switching to lower case r is the same as removing it (as suggested by BagOfIce). Download V37 and keep the capital R and everything should be fixed.

**Comment by Larrush** [comment] 2019-04-20 22:21
Oh, my bad ^^ I thought I had this figured out xD

Thanks for the quick fix and the help! 
With the new version it works fine so far.

The only thing is that the bot shows V36 on startup
`<2019/04/21 00:15:33> BHBot v36 build on Sun Apr 21 00:08:41 CEST 2019 started.`

This is not an issue, but I thought I´d mention it :)

**Comment by ilpersi** [comment] 2019-04-20 22:35
My bad, I rushed the release and forgot to update the internal version number.
V37.1 now displays the correct version number at startup time.

**Closed** 2019-04-21 21:08 UTC
Labels: bug
