### ISSUE TITLE
tankPriority buying potions with gems

### ISSUE THREAD

**Issue by Fortigate** [Betalord/BHBot#52] opened 2019-04-13 08:50 UTC
Was wondering why one of my accounts never had gems.. if you have medium potions but no large potions the bot will click the large potions, and then click the yes button for _purchase_ potions instead of _use_ potion, spending 200gems on a large revive. ouch.

**Comment by ilpersi** [comment] 2019-04-13 09:03
I was reviewing autorevive code and there is really few fails safe and it is all based on clickInGame instead of using cue detection.

IMHO opinion some rewrite is required, I can look at it when I have more time.

**Comment by Fortigate** [comment] 2019-04-13 09:28
I might be able to have a look at it, in this case it looks for the green yes button which is the same in both dialogues. The systems pretty hacky you're right, could use a passover.

**Comment by Fortigate** [comment] 2019-04-13 21:16
Looks like I left it unfinished as I had 100's of every potion when I wrote it. When the purchase dialogue is detected it should close the window and try the next potion as of https://github.com/Betalord/BHBot/commit/1301d70d330c7e686b03166078f95293daf062b6.

**Comment by ilpersi** [comment] 2019-04-13 22:29
Checkout commit b22db4913c123513d268ef008a8e701e3734a348.

New EXPERIMENTAL autoRevive system:
* rewrote from scratch
* completely fail-safe
* should fix the tank priory issue reported here (I could not reproduce it)
* can resurrect more than one team member in a row
* disabled by default, it can be enabled by adding this line to settings.ini `experimentalAutoRevive 1`

I did not have the required time to test it carefully, this is why I released it as experimental.

I don't have a screenshot with no potions (I've never used them so I have plenty), if you can share that I can add even more fail-safe.

**Comment by Fortigate** [comment] 2019-04-13 23:33
Looking really good, I'll test it out on my alt accounts. Next time I run out I'll get screengrabs of the greyed out potions.

**Comment by Fortigate** [comment] 2019-04-19 14:51
New system looks great, only two issues I'm having:

It seems to get activated in PvP occasionally
With potionOrder 213 and no Medium potions it uses Major revives instead of Minor

**Comment by ilpersi** [comment] 2019-04-19 20:26
I fixed PVP with commit e3d2047039a36b11bd77301625452eddaed32123 and for the potionOrder issue it may just be a wrong message as the logic is right, I will try to improve this.

**Comment by ilpersi** [comment] 2019-04-23 15:44
tankPriority is working fine now, I am closing this. I'll leave #40 opened to discuss about the auto functionalities.

**Closed by ilpersi** 2019-04-23 15:44 UTC
Labels: bug
