### ISSUE TITLE
AutoShrine on dungeons/autorevive

### ISSUE THREAD

**Issue by Larrush** [Betalord/BHBot#40] opened 2019-03-18 22:34 UTC
Sry for reposting, but I wasn´t sure if anybody saw it in the other post "autofunctions" 

He enables autoshrine, doesn´t have enough points, but forgets to deactivate it and starts a dungeon, which he never passes due to him not realising he has to deactivate it

![Untitled](https://user-images.githubusercontent.com/47528224/54494043-6d920c80-48d6-11e9-85b2-e56309be2450.jpg)
![Untitled](https://user-images.githubusercontent.com/47528224/54494051-8995ae00-48d6-11e9-8d3a-da685835d28e.jpg)

I have the newest master, so it seems he still gets confused by this 

_Originally posted by @Larrush in https://github.com/Betalord/BHBot/issues/29#issuecomment-473679618_

Also there is one small issue with autorevive. If 2 or more players die at the same time, he only revives one of them.
I guess he is just not expecting that the one behind could also be dead.

Not a big Issue, just thought I´d mention it ^^

**Comment by Fortigate** [comment] 2019-03-22 11:19
I'll have some time this weekend to go over the autoshrine code and add in some failssafes/check the logic

**Comment by Larrush** [comment] 2019-03-24 23:36
It would also be nice to have the autoshrine and revive function for expeditions ^^ 😅

**Comment by Larrush** [comment] 2019-03-29 11:26
```
<2019/03/29 12:22:37> World Boss completed successfully. Result: Victory
<2019/03/29 12:22:39> Enabling Ignore Boss
<2019/03/29 12:22:39> Enabling Ignore Shrine
<2019/03/29 12:22:40> autoShrine autoConfigured
<2019/03/29 12:22:43> Shards: 0, required: >0
<2019/03/29 12:22:45> Energy: 25%, required: >4%
<2019/03/29 12:22:46> Attempting Normal T10 Melvin. Lobby timeout is 60s.
<2019/03/29 12:22:58> Starting lobby
```

This also seems to happen between Worldboss, so if there is "dungeon after lobbytimeout" active he could get stuck in a dungeon

**Comment by Larrush** [comment] 2019-04-01 08:11
Short question, what language would I have to learn to help out with the code? 
I mean, I could at least try to fix the autoshrine bug for me, and maybe it works for others too if I find a good solution.
And maybe I can even help out more If I understand what I am doing ^^

**Comment by Fortigate** [comment] 2019-04-08 11:52
Java ideally but if you know any coding you should be able to read and understand the code quite quickly, I hadn't used Java before I started working on this bot. Many functions and features use the same basic template so you can chop and change and add parts quite easily in the code without worrying too much. @ilpersi is a wizard so worse case scenario he can tidy up/make suggestions to anything you add.

**Comment by ilpersi** [comment] 2019-04-08 16:00
I don't use this feature myself, so I am not exactly clear what the bug is.

@Fortigate are you still looking at this? PS: this is my first Java project as well. ;)

**Comment by ilpersi** [comment] 2019-04-10 07:54
@Larrush I made some improvements to the autoShrine functionality. With the latest master I had the bot running for 12 hours with no issues so far.

**Comment by Larrush** [comment] 2019-04-10 10:34
I just downloaded it and tried it out and so far the first run went fluent without any issues.

He still got confused when gvg came after the "autoshrine on check", but in GVG he doesn´t get stuck due to this so I really don´t mind ;)

Thanks for fixing this issue, since it can really help with pushing further in trials/raids! Really appreciate the effort :D

**Comment by ilpersi** [comment] 2019-04-10 13:32
> He still got confused when gvg came after the "autoshrine on check", but in GVG he doesn´t get stuck due to this so I really don´t mind ;)

@Larrush 
Can you please clarify this?

There are still a couple of failsafe that I would like to add, but the logic should be the following:
* at startup time the bot makes sure that everything is disable
* Ignore boss & Ignore shrines are the enabled before: raids, trials, expedition
* After 60 seconds that it is out of the last encounter it initially disables the ignore shrines, wait 20 seconds and disable the ignore boss

I have almost 24h straight with no issues so far

**Comment by Larrush** [comment] 2019-04-11 20:23
@ilpersi 
I am not sure anymore if it was in the middle of GVG or before but basically he would do this:

```
Raid completed succesfully
Autoshrine configured on
Ignore Shrine/Boss active
Check points
Not enough points
(Missing "unchecking Shrine/Boss") 
Start Gvg
...
```

So in case he would do Dungeon after, he might not check if Shrine/Boss is on on or not. 
This only happened once so far.

But I just realised there is probably another failsafe if he starts a dungeon^^ 

So far I didn´t had any problems with autoshrine. I think it works pretty well now :) 

Thanks for checking this feature!

**Comment by ilpersi** [comment] 2019-04-12 10:25
This is good news, the autoRevive feature needs some refactoring as well to fix the two dead people issue, as I get some time I will look in to it.

**Comment by Larrush** [comment] 2019-04-12 23:24
Since this hardly ever happens, there is no need to rush :) 

So I finally witnessed it again, when doing gvg he does this:

```
<2019/04/13 01:12:30> GVG completed successfully. Result: Victory
<2019/04/13 01:12:32> Enabling Ignore Boss
<2019/04/13 01:12:32> Enabling Ignore Shrine
<2019/04/13 01:12:33> autoShrine autoConfigured
<2019/04/13 01:12:36> Shards: 0, required: >0
<2019/04/13 01:12:41> Badges: 2, required: >0
<2019/04/13 01:12:41> Attempting GVG...
```

So it seems that when checking raids in between gvg, he doesn´t uncheck the shrine/boss feature.
But since he usually checks for trials afterwards, he does uncheck it afterwards for me the whole line looked like this: 

```
<2019/04/13 01:12:30> GVG completed successfully. Result: Victory
<2019/04/13 01:12:32> Enabling Ignore Boss
<2019/04/13 01:12:32> Enabling Ignore Shrine
<2019/04/13 01:12:33> autoShrine autoConfigured
<2019/04/13 01:12:36> Shards: 0, required: >0
<2019/04/13 01:12:41> Badges: 2, required: >0
<2019/04/13 01:12:41> Attempting GVG...
<2019/04/13 01:13:10> GVG initiated!
<2019/04/13 01:13:44> GVG completed successfully. Result: Victory
<2019/04/13 01:13:47> Badges: 1, required: >0
<2019/04/13 01:13:47> Attempting GVG...
<2019/04/13 01:14:15> GVG initiated!
<2019/04/13 01:14:41> GVG completed successfully. Result: Victory
<2019/04/13 01:14:44> Ignore Boss Enabled
<2019/04/13 01:14:44> Ignore Shrine Enabled
<2019/04/13 01:14:45> autoShrine autoConfigured
<2019/04/13 01:14:50> Tokens: 0, required: >0
<2019/04/13 01:14:53> Disabling Ignore Boss
<2019/04/13 01:14:53> Disabling Ignore Shrine
<2019/04/13 01:14:54> autoShrine disabled
<2019/04/13 01:14:57> Energy: 61%, required: >4%
<2019/04/13 01:14:58> Attempting Normal T10 Melvin. Lobby timeout is 60s.
<2019/04/13 01:15:11> Starting lobby
```

and so on.

**Comment by ilpersi** [comment] 2019-04-13 06:16
GVG is over and I wont be able to reproduce it, so I've added more logs that explain why autoShrine is being enabled, hopefully this should help next time.

Despite this I've found a bug with gauntlet and I've just fixed that.

**Comment by ilpersi** [comment] 2019-04-13 22:26
Checkout commit b22db4913c123513d268ef008a8e701e3734a348.

New EXPERIMENTAL autoRevive system:
* rewrote from scratch
* completely fail-safe
* fixes the two dead people bug reported in this thread
* can resurrect more than one team member in a row
* disabled by default, it can be enabled by adding this line to settings.ini `experimentalAutoRevive 1`

I did not have the required time to test it carefully, this is why I released it as experimental.

**Comment by Larrush** [comment] 2019-04-14 01:47
Thanks alot! 
I just downloaded it and activated the experimental feature :) 
I´ll tell you how it goes for me!

**Comment by Larrush** [comment] 2019-04-14 21:59
So after about 200 raids since yesterday I would say the new system works very well :)

I haven't found any issues.
I turned it on yesterday at night and it finished somewhen today.

**Comment by ilpersi** [comment] 2019-04-15 08:42
This is really good news! :)
I had good results as well, so I am going to make the new autoRevive system the default one in the upcoming commits.

I leave this open as with GVGV there still seems to be issues with autoShrine. For the moment I've been running it straight with no issues. One question: was the autoshrine enabled when you run the 200 raids?

**Comment by Larrush** [comment] 2019-04-15 17:13
Yes it was too and so far I didn't recognize any problems as it is now! :)

**Comment by Larrush** [comment] 2019-04-17 22:52
I´ve found one more Issue with autoshrine

When having Expedition activated, even though it´s not available he does this:

```
<2019/04/18 00:43:18> Enabling Ignore Boss
<2019/04/18 00:43:18> Enabling Ignore Shrine
<2019/04/18 00:43:19> autoShrine autoConfigured
<2019/04/18 00:43:22> Shards: 0, required: >0
<2019/04/18 00:43:24> Expedition button not found
<2019/04/18 00:43:28> Tokens: 2, required: >0
<2019/04/18 00:43:30> Energy: 9%, required: >4%
<2019/04/18 00:43:35> Attempting Heroic z1d1
<2019/04/18 00:43:41> Zone less than dungeon solo threshold, attempting solo
<2019/04/18 00:43:46> Dungeon <z1d1> initiated solo!
```

I guess because the Expedition is not available he doesn´t remember he activated it in the first place.

And I also think the safecheck for dungeons when beeing inactive for too long doesn´t work either, since I´ve been waiting for a while now and nothing happened so far.

**Comment by ilpersi** [comment] 2019-04-18 13:44
From the log I see you are using v34 of the bot or a self compiled version of the bot not up do date.

Make sure to update to the latest [v36](https://github.com/Betalord/BHBot/releases/tag/v36).

**Comment by Larrush** [comment] 2019-04-18 15:41
I have a self compiled version, but I think I didn't update the java file.

I'll fix that tonight and come back to you!

**Comment by ilpersi** [comment] 2019-04-18 21:49
The latest version is now printing at start time:
* the build time
* the GIT commit ID on which is built
* teh GIT time so to meke t

**Comment by eschwim** [comment] 2019-04-20 08:08
Can we get autorevive for expeditions, too? :)

**Comment by ilpersi** [comment] 2019-04-26 16:10
I've been using the auto functions for very long time now without issues so far so I am going to close this issue. If any new problem arise with auto functions, please open a new one.

**Closed by ilpersi** 2019-04-26 16:10 UTC
Labels: bug
